version: 1

formatters:
  basic:
    format: "[%(threadName)s] %(message)s"

handlers:
  console:
    class: pims.logger.PimsHandler
    level: INFO
    formatter: basic
    rich_tracebacks: True
    markup: True

loggers:
  pims:
    level: INFO
    handlers: [console]
    propagate: false
  pyvips:
    level: ERROR
    handlers: [console]
    propagate: false
  uvicorn:
    level: INFO
    handlers: [console]
    propagate: false
  uvicorn.access:
    level: CRITICAL
    handlers:

root:
  handlers: [console]
  level: INFO
